# Generated by Django 4.1.5 on 2023-03-13 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('profession_title', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('photo', models.ImageField(null=True, upload_to='candidate_photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='candidate_videos/')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='candidate_featured_images/')),
                ('skills', models.TextField(null=True)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('resume', models.FileField(null=True, upload_to='candidate_resumes/')),
                ('short_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('tagline', models.CharField(max_length=200)),
                ('video', models.FileField(blank=True, null=True, upload_to='media/company_videos/')),
                ('logo', models.ImageField(upload_to='media/company_logos/')),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('team_size', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('date_started', models.DateField()),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Remote', 'Remote')], max_length=20)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/job_images/')),
                ('link', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kazi.jobcategory')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kazi.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kazi.company')),
                ('job_listings', models.ManyToManyField(to='kazi.joblist')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kazi.jobcategory'),
        ),
        migrations.CreateModel(
            name='BackgroundData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('work_start_date', models.DateField()),
                ('work_end_date', models.DateField()),
                ('institution', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('institution_start_date', models.DateField()),
                ('institution_end_date', models.DateField()),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='kazi.candidate')),
            ],
        ),
    ]
