# Generated by Django 4.1.5 on 2023-03-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazi', '0002_candidate_jobcategory_candidate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='description',
            field=models.TextField(blank=True, choices=[('Accounting and Finance', 'Financial analysis'), ('Accounting and Finance', 'Audit and taxation'), ('Accounting and Finance', 'Accounts payable/receivable'), ('Administration and Office Support', 'Executive assistance'), ('Administration and Office Support', 'Office management'), ('Administration and Office Support', 'Reception and switchboard'), ('Architecture and Engineering', 'Civil engineering'), ('Architecture and Engineering', 'Mechanical engineering'), ('Architecture and Engineering', 'Electrical engineering'), ('Arts and Design', 'Graphic design'), ('Arts and Design', 'Photography'), ('Arts and Design', 'Art direction'), ('Business and Management', 'Sales and marketing management'), ('Business and Management', 'Operations management'), ('Business and Management', 'Project management'), ('Construction and Trades', 'Plumbing'), ('Construction and Trades', 'Electrical'), ('Construction and Trades', 'Carpentry'), ('Customer Service', 'Call center'), ('Customer Service', 'Helpdesk support'), ('Customer Service', 'Technical support'), ('Education and Training', 'Teaching and lecturing'), ('Education and Training', 'Curriculum development'), ('Education and Training', 'Training and development'), ('Healthcare and Medical', 'Nursing'), ('Healthcare and Medical', 'Pharmacy'), ('Healthcare and Medical', 'Medical laboratory'), ('Hospitality and Tourism', 'Hotel and restaurant management'), ('Hospitality and Tourism', 'Tourism and travel'), ('Hospitality and Tourism', 'Food and beverage service'), ('Human Resources', 'Recruitment and talent acquisition'), ('Human Resources', 'Employee relations'), ('Human Resources', 'Compensation and benefits'), ('Information Technology', 'Software development'), ('Information Technology', 'Network engineering'), ('Information Technology', 'Cybersecurity'), ('Legal', 'Corporate law'), ('Legal', 'Litigation'), ('Legal', 'Intellectual property'), ('Marketing and Communications', 'Public relations'), ('Marketing and Communications', 'Brand management'), ('Marketing and Communications', 'Digital marketing'), ('Non-profit and Volunteer', 'Fundraising and development'), ('Non-profit and Volunteer', 'Community outreach'), ('Non-profit and Volunteer', 'Volunteer management'), ('Retail and Sales', 'Retail management'), ('Retail and Sales', 'Sales representative'), ('Retail and Sales', 'Merchandising'), ('Science and Technology', 'Research and development'), ('Science and Technology', 'Data analysis'), ('Science and Technology', 'Biotechnology'), ('Social Services', 'Social work'), ('Social Services', 'Counseling'), ('Social Services', 'Case management'), ('Transportation and Logistics', 'Truck driving'), ('Transportation and Logistics', 'Supply chain management'), ('Transportation and Logistics', 'Warehouse operations')]),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(choices=[('Accounting and Finance', 'Accounting and Finance'), ('Administration and Office Support', 'Administration and Office Support'), ('Architecture and Engineering', 'Architecture and Engineering'), ('Arts and Design', 'Arts and Design'), ('Business and Management', 'Business and Management'), ('Construction and Trades', 'Construction and Trades'), ('Customer Service', 'Customer Service'), ('Education and Training', 'Education and Training'), ('Healthcare and Medical', 'Healthcare and Medical'), ('Hospitality and Tourism', 'Hospitality and Tourism'), ('Human Resources', 'Human Resources'), ('Information Technology', 'Information Technology'), ('Legal', 'Legal'), ('Marketing and Communications', 'Marketing and Communications'), ('Non-profit and Volunteer', 'Non-profit and Volunteer'), ('Retail and Sales', 'Retail and Sales'), ('Science and Technology', 'Science and Technology'), ('Social Services', 'Social Services'), ('Transportation and Logistics', 'Transportation and Logistics')], max_length=50),
        ),
    ]
