# Generated by Django 4.1.5 on 2023-03-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kazi', '0003_alter_jobcategory_description_alter_jobcategory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcategory',
            old_name='description',
            new_name='job_subcategory',
        ),
    ]
