# Generated by Django 4.1.5 on 2023-03-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazi', '0006_remove_jobcategory_name_jobcategory_job_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='other_job_category',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='other_job_subcategory',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
