# Generated by Django 4.1.5 on 2023-03-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazi', '0010_delete_jobsubcategory_jobcategory_job_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='job_subcategory',
            field=models.CharField(default='other', max_length=50),
        ),
    ]
