# Generated by Django 4.1.5 on 2023-03-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazi', '0011_alter_jobcategory_job_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='job_subcategory',
            field=models.CharField(choices=[], default='other', max_length=50),
        ),
    ]
