# Generated by Django 4.1.5 on 2023-03-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazi', '0012_alter_jobcategory_job_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='rate_per_hour',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='job_subcategory',
            field=models.CharField(choices=[('Financial analysis', 'Financial analysis'), ('Audit and taxation', 'Audit and taxation'), ('Accounts payable/receivable', 'Accounts payable/receivable'), ('Executive assistance', 'Executive assistance'), ('Office management', 'Office management'), ('Reception and switchboard', 'Reception and switchboard'), ('Civil engineering', 'Civil engineering'), ('Mechanical engineering', 'Mechanical engineering'), ('Electrical engineering', 'Electrical engineering'), ('Graphic design', 'Graphic design'), ('Photography', 'Photography'), ('Art direction', 'Art direction'), ('Sales and marketing management', 'Sales and marketing management'), ('Operations management', 'Operations management'), ('Project management', 'Project management'), ('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Carpentry', 'Carpentry'), ('Call center', 'Call center'), ('Helpdesk support', 'Helpdesk support'), ('Technical support', 'Technical support'), ('Teaching and lecturing', 'Teaching and lecturing'), ('Curriculum development', 'Curriculum development'), ('Training and development', 'Training and development'), ('Nursing', 'Nursing'), ('Pharmacy', 'Pharmacy'), ('Medical laboratory', 'Medical laboratory'), ('Hotel and restaurant management', 'Hotel and restaurant management'), ('Tourism and travel', 'Tourism and travel'), ('Food and beverage service', 'Food and beverage service'), ('Recruitment and talent acquisition', 'Recruitment and talent acquisition'), ('Employee relations', 'Employee relations'), ('Compensation and benefits', 'Compensation and benefits'), ('Software development', 'Software development'), ('Network engineering', 'Network engineering'), ('Cybersecurity', 'Cybersecurity'), ('Corporate law', 'Corporate law'), ('Litigation', 'Litigation'), ('Intellectual property', 'Intellectual property'), ('Public relations', 'Public relations'), ('Brand management', 'Brand management'), ('Digital marketing', 'Digital marketing'), ('Fundraising and development', 'Fundraising and development'), ('Community outreach', 'Community outreach'), ('Volunteer management', 'Volunteer management'), ('Retail management', 'Retail management'), ('Sales representative', 'Sales representative'), ('Merchandising', 'Merchandising'), ('Research and development', 'Research and development'), ('Data analysis', 'Data analysis'), ('Biotechnology', 'Biotechnology'), ('Social work', 'Social work'), ('Counseling', 'Counseling'), ('Case management', 'Case management'), ('Truck driving', 'Truck driving'), ('Supply chain management', 'Supply chain management'), ('Warehouse operations', 'Warehouse operations'), ('other', 'other')], default='other', max_length=50),
        ),
    ]
