# Generated by Django 4.1.5 on 2023-03-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazi', '0013_alter_candidate_rate_per_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='rate_per_hour',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
