# Generated by Django 4.1.5 on 2023-03-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazi', '0014_alter_joblist_rate_per_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='rate_per_hour',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='rate_per_hour',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
