# Generated by Django 4.1.6 on 2023-03-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazi', '0017_jobcategory_bootstrap_icon_jobcategory_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='bootstrap_icon',
            field=models.CharField(blank=True, default='fa-solid fa-paperclip', max_length=50, null=True),
        ),
    ]
